version: '3'
services:
  robo-bb-service:
    container_name: robo-bb
    build: .
    restart: always
    command: npm run start:dev
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app


      